-- create the tables

CREATE TABLE users (
  id bigint generated by default as identity not null,
  email varchar(128),
  password_hash varchar(64),
  first_login_date timestamp,
  last_login_date timestamp,
  primary key (id)
);

CREATE TABLE roles (
  id bigint generated by default as identity not null,
  name varchar(32) not null,
  primary key (id)
);

CREATE TABLE users_roles (
  user_id bigint not null,
  role_id bigint not null
);

-- add constraints

ALTER TABLE users add constraint users_email_unique unique (email);
ALTER TABLE roles add constraint roles_name_unique unique (name);
ALTER TABLE users_roles add constraint users_roles_both_unique unique (user_id, role_id);
ALTER TABLE users_roles add constraint users_roles_user_fk foreign key (user_id) references users;
ALTER TABLE users_roles add constraint users_roles_role_fk foreign key (role_id) references roles;

-- insert the default users

INSERT INTO users (id, email, password_hash, first_login_date)
  VALUES (1, 'comixedadmin@localhost', '6363600A9EB85946D3206394F9D603B1', NOW());
INSERT INTO users (id, email, password_hash, first_login_date)
  VALUES (2, 'comixedreader@localhost', 'ED6563287430EC477A9475D99EA6BC59', NOW());
INSERT INTO roles (id, name)
  VALUES (1, 'ADMIN'),
         (2, 'READER');
INSERT INTO users_roles (user_id, role_id)
  VALUES (1, 1),
         (1, 2),
         (2, 2);