-- create the table

CREATE TABLE blocked_page_hashes(
	id bigint generated by default as identity not null,
	hash varchar(32) not null,
	primary key (id)
);

ALTER TABLE blocked_page_hashes add constraint blocked_page_hashes_hash_unique unique (hash);

