-- create the table

CREATE TABLE comic_credits(
	id bigint generated by default as identity not null,
	comic_id bigint,
	name varchar(128) not null,
	role varchar(128) not null,
	primary key (id)
);

ALTER TABLE comic_credits add constraint comic_credits_comic_fk foreign key (comic_id) references comics;
