-- create the scan_types table

CREATE TABLE scan_types(
    id bigint generated by default as identity not null,
    name varchar(32) not null,
    primary key (id)
);

ALTER TABLE scan_types add constraint scan_types_name_unique unique (name);

INSERT INTO scan_types (id, name) 
	VALUES (1, 'digital'),
           (2, 'print'),
           (3, 'print_c2c'),
           (4, 'fiche'),
           (5, 'hybrid'),
           (6, 'partial'),
           (7, 'scanalation');

-- create the format table

CREATE TABLE comic_formats(
    id bigint generated by default as identity not null,
    name varchar(32) not null,
    primary key (id)
);

ALTER TABLE comic_formats add constraint comic_formats_name_unique unique(name);

INSERT INTO comic_formats (id, name)
    VALUES (1, 'standard'),
           (2, 'trade-paperback'),
           (3, 'graphic-novel'),
           (4, 'deluxe-edition'),
           (5, 'treasury'),
           (6, 'digest'),
           (7, 'preview'),
           (8, 'promotional'),
           (9, 'unpublished'),
           (10, 'book'),
           (11, 'magazine'),
           (12, 'manga-left'),
           (13, 'manga-right');

-- add columns to the comics table

ALTER TABLE comics add scan_type_id bigint;
ALTER TABLE comics add constraint comics_scan_types foreign key (scan_type_id) references scan_types;

ALTER TABLE comics add imprint varchar(255);

ALTER TABLE comics add format_id bigint;
ALTER TABLE comics add constraint comics_format_type foreign key (format_id) references comic_formats;

-- add default values to the comics table
UPDATE comics SET format_id=1;
