-- create the reading list tables

CREATE TABLE reading_lists(
    id bigint generated by default as identity not null,
    name varchar(128) not null,
    owner_id bigint not null,
    summary varchar(256),
    created timestamp not null,
    primary key (id)
);

CREATE TABLE reading_list_entries(
	id bigint generated by default as identity not null,
    reading_list_id bigint not null,
    comic_id bigint not null,
    added timestamp not null,
    primary key (id)
);

ALTER TABLE reading_lists add constraint reading_lists_owner_fk foreign key (owner_id) references users;
ALTER TABLE reading_list_entries add constraint reading_list_entries_reading_list_fk foreign key (reading_list_id) references reading_lists;
ALTER TABLE reading_list_entries add constraint reading_list_entries_comic_fk foreign key (comic_id) references comics;