-- create the tables

CREATE TABLE comics (
  id bigint generated by default as identity not null,
  archive_type varchar(255),
  comic_vine_id varchar(255),
  comic_vine_url varchar(255),
  cover_date date,
  added_date timestamp not null,
  filename varchar(1024) not null,
  issue_number varchar(255),
  last_read_date timestamp,
  publisher varchar(255),
  series varchar(255),
  title varchar(255),
  volume varchar(255),
  description clob,
  notes clob,
  summary clob,
  primary key (id)
);

CREATE TABLE pages (
  id bigint generated by default as identity,
  deleted boolean not null,
  filename varchar(255) not null,
  hash varchar(255) not null,
  height integer,
  width integer,
  comic_id bigint,
  index integer,
  primary key (id)
 );
 
 CREATE TABLE comic_characters (
  comic_id bigint not null,
  character_name varchar(255)
 );

CREATE TABLE comic_locations (
  comic_id bigint not null,
  location_name varchar(255)
 );

CREATE TABLE comic_story_arcs (
  comic_id bigint not null,
  story_arc_name varchar(255)
);

CREATE TABLE comic_teams (
  comic_id bigint not null,
  team_name varchar(255)
);

ALTER TABLE comics add constraint comics_filename_unique unique (filename);
ALTER TABLE comic_characters add constraint comic_characters_comic_fk foreign key (comic_id) references comics;
ALTER TABLE comic_locations add constraint comic_locations_comic_fk foreign key (comic_id) references comics;
ALTER TABLE comic_story_arcs add constraint comic_story_arcs_comic_fk foreign key (comic_id) references comics;
ALTER TABLE comic_teams add constraint comic_teams_comic_fk foreign key (comic_id) references comics;
ALTER TABLE pages add constraint pages_comic_fk foreign key (comic_id) references comics;
