-- create the table

CREATE TABLE block_page_hashes(
	id bigint generated by default as identity not null,
	hash varchar(32) not null,
	primary key (id)
);

ALTER TABLE block_page_hashes add constraint block_page_hashes_name_unique unique (hash);

