-- create the scan_types table

CREATE TABLE scan_types(
    id bigint generated by default as identity not null,
    name varchar(32) not null,
    primary key (id)
);

ALTER TABLE scan_types add constraint scan_types_name_unique unique (name);

INSERT INTO scan_types (id, name) 
	VALUES (1, 'digital'),
           (2, 'print'),
           (3, 'print_c2c'),
           (4, 'fiche'),
           (5, 'hybrid'),
           (6, 'partial'),
           (7, 'scanalation');

-- add columns to the comics table

ALTER TABLE comics add scan_type_id bigint;
ALTER TABLE comics add constraint comics_scan_types foreign key (scan_type_id) references scan_types;
