-- remove the last_read column from the comics table
ALTER TABLE comics drop column last_read_date;

-- create the table

CREATE TABLE user_last_read_dates(
	id bigint generated by default as identity not null,
	user_id bigint not null,
	comic_id bigint not null,
	last_read timestamp not null,
	primary key (id)
);

ALTER TABLE user_last_read_dates add constraint user_last_read_dates_user_fk foreign key (user_id) references users;
ALTER TABLE user_last_read_dates add constraint user_last_read_dates_comic_fk foreign key (comic_id) references comics;
