name: Build and release
on:
  push:
    branches:
      - feature/issue-291
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  changelog:
    # Job name is Chanegelog
    name: Chanegelog Generator
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: homeday-de/github-action-changelog-generator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
