name: Build and release
on:
  push:
    branches:
      - feature/issue-291
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    if: github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels.*.name), '"autorelease"')
    runs-on: ubuntu-latest
    env:
      manifest_file: 'manifest.yml'
      changelog_file: 'CHANGELOG.md'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          git fetch --prune --unshallow
      - name: Create changelogs
        id: changelogs
        uses: heineiuo/create-changelogs@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelogs.outputs.changelog_text }}
          draft: false
          prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}
