name: development

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      run: mvn -B package --file pom.xml -P ci -DskipTests
    - name: Publish release artifacts
      uses: actions/upload-artifact@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release Binaries
        path: comixed-app/target/artifacts